TYPO3:
  SwiftMailer:
    transport:
      type: 'TYPO3\SwiftMailer\Transport\MboxTransport'
      options:
        mboxPathAndFilename: '%FLOW_PATH_DATA%/Persistent/SentMails'
  Flow:
    object:
      excludeClasses:
        'codeception.codeception': ['.*']
        'oliverhader.flowception': ['.*']
        'react.promise': ['.*']
        'guzzlehttp.*': ['.*']
        'site5.*': ['.*']
